### ISSUE TITLE
gh action and gh integration not working

### ISSUE THREAD

**Issue by pranaysahith** [cypress-io/gh-action-and-gh-integration#13]
Hi, I have enabled github integration in cypress, but the cypress is not commenting test results.
What env variables are used by cypress to identify the gh pull request to add comments?

**Comment by jennifer-shehane** [comment]
@pranaysahith GitHub Integration is dependent on your CI environment reliably providing commit SHA data (typically via an environment variable). This is not a problem for most people, but if you are facing GitHub integration issues with your CI setup, you'll want to make sure the git information is being sent properly by following [these guidelines](https://on.cypress.io/continuous-integration#Environment-variables).

**Comment by pranaysahith** [comment]
I have set the environment variables given here - https://docs.cypress.io/guides/guides/continuous-integration.html#Git-information, but cypress is still not commenting the PR.
Can you please, precisely tell me how cypress determines which PR it has to comment the test results?

**Comment by jennifer-shehane** [comment]
@pranaysahith Cypress specifically looks for the `COMMIT_INFO_SHA` and associates that back to the GitHub PR.
